$(document).ready(function(){
    $('i.fa-bars').click(function(){
        $('.hamburger-menu').toggle(function(){
            $('.hamburger-menu').fadeIn(2000);
            $('i.fa-times').click(function(){
                $('.hamburger-menu').fadeOut(1000);
            });
        });
    });
});